# Generated by Django 4.2.3 on 2024-01-18 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_studentmodel_aadhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='aadhar_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.aadharmodel'),
        ),
    ]
